[package]
name = "always-success"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-std = "0.16.2"

[profile.release]
overflow-checks = true
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
